[2025-04-04T04:25:37.095+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-04T04:24:11.887988+00:00/task_id=training_with_random_forest_model permission to 509
[2025-04-04T04:25:37.136+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-04T04:24:11.887988+00:00/task_id=training_with_random_forest_model permission to 509
[2025-04-04T04:25:37.188+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_random_forest_model manual__2025-04-04T04:24:11.887988+00:00 [queued]>
[2025-04-04T04:25:37.206+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_random_forest_model manual__2025-04-04T04:24:11.887988+00:00 [queued]>
[2025-04-04T04:25:37.207+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-04-04T04:25:37.257+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_with_random_forest_model> on 2025-04-04 04:24:11.887988+00:00
[2025-04-04T04:25:37.268+0000] {standard_task_runner.py:57} INFO - Started process 725 to run task
[2025-04-04T04:25:37.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_with_random_forest_model', 'manual__2025-04-04T04:24:11.887988+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmp5gud5081']
[2025-04-04T04:25:37.285+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask training_with_random_forest_model
[2025-04-04T04:25:37.444+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-04T04:24:11.887988+00:00/task_id=training_with_random_forest_model permission to 509
[2025-04-04T04:25:37.447+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_with_random_forest_model manual__2025-04-04T04:24:11.887988+00:00 [running]> on host d8a8722a294d
[2025-04-04T04:25:37.561+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_with_random_forest_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T04:24:11.887988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T04:24:11.887988+00:00'
[2025-04-04T04:25:41.822+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:25:41 INFO mlflow.tracking.fluent: Experiment with name 'Random_forest_looking_for_the_best_model' does not exist. Creating a new experiment.
[2025-04-04T04:25:42.176+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:25:42 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-04-04T04:25:42.309+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:25:42 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-04T04:25:42.969+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2025-04-04T04:33:09.287+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-04-04T04:33:14.759+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:33:14 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-04-04T04:33:16.273+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:33:16 INFO mlflow.sklearn.utils: Logging the 5 best runs, 22 runs will be omitted.
[2025-04-04T04:33:16.727+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-04-04T04:33:16.738+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_with_random_forest_model, execution_date=20250404T042411, start_date=20250404T042537, end_date=20250404T043316
[2025-04-04T04:33:16.822+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-04-04T04:33:16.846+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
