[2025-04-04T04:25:32.909+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-04T04:24:11.887988+00:00/task_id=training_with_gradient_boosting_model permission to 509
[2025-04-04T04:25:32.942+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-04T04:24:11.887988+00:00/task_id=training_with_gradient_boosting_model permission to 509
[2025-04-04T04:25:32.981+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-04-04T04:24:11.887988+00:00 [queued]>
[2025-04-04T04:25:32.991+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-04-04T04:24:11.887988+00:00 [queued]>
[2025-04-04T04:25:32.994+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-04-04T04:25:33.008+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_with_gradient_boosting_model> on 2025-04-04 04:24:11.887988+00:00
[2025-04-04T04:25:33.023+0000] {standard_task_runner.py:57} INFO - Started process 715 to run task
[2025-04-04T04:25:33.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_with_gradient_boosting_model', 'manual__2025-04-04T04:24:11.887988+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmp_qbheyp2']
[2025-04-04T04:25:33.029+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask training_with_gradient_boosting_model
[2025-04-04T04:25:33.088+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-04T04:24:11.887988+00:00/task_id=training_with_gradient_boosting_model permission to 509
[2025-04-04T04:25:33.091+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-04-04T04:24:11.887988+00:00 [running]> on host d8a8722a294d
[2025-04-04T04:25:33.174+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_with_gradient_boosting_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T04:24:11.887988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T04:24:11.887988+00:00'
[2025-04-04T04:25:36.866+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:25:36 INFO mlflow.tracking.fluent: Experiment with name 'Gradient_Boosting_looking_for_the_best_model' does not exist. Creating a new experiment.
[2025-04-04T04:25:39.233+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:25:39 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-04-04T04:25:39.356+0000] {logging_mixin.py:149} WARNING - 2025/04/04 04:25:39 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-04T04:25:40.701+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2025-04-05T16:51:28.122+0000] {local_task_job_runner.py:298} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-05T16:51:28.845+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 715. PIDs of all processes in the group: [715]
[2025-04-05T16:51:28.865+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 715
[2025-04-05T16:51:28.945+0000] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-05T16:52:24.352+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=715, name='airflow task ru', status='running', started='2025-04-04 04:25:32') did not respond to SIGTERM. Trying SIGKILL
[2025-04-05T16:52:24.368+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 715
[2025-04-05T16:52:24.468+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=715, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='2025-04-04 04:25:32') (715) terminated with exit code Negsignal.SIGKILL
[2025-04-05T16:52:24.472+0000] {standard_task_runner.py:172} ERROR - Job 6 was killed before it finished (likely due to running out of memory)
