[2025-04-05T17:15:53.884+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-05T17:14:18.319793+00:00/task_id=training_modelos_de_prueba permission to 509
[2025-04-05T17:15:53.946+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-05T17:14:18.319793+00:00/task_id=training_modelos_de_prueba permission to 509
[2025-04-05T17:15:53.995+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-04-05T17:14:18.319793+00:00 [queued]>
[2025-04-05T17:15:54.027+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-04-05T17:14:18.319793+00:00 [queued]>
[2025-04-05T17:15:54.029+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-04-05T17:15:54.061+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_de_prueba> on 2025-04-05 17:14:18.319793+00:00
[2025-04-05T17:15:54.080+0000] {standard_task_runner.py:57} INFO - Started process 2061 to run task
[2025-04-05T17:15:54.098+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_modelos_de_prueba', 'manual__2025-04-05T17:14:18.319793+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpnjegwn4j']
[2025-04-05T17:15:54.137+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask training_modelos_de_prueba
[2025-04-05T17:15:54.414+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=Pipeline-proyecto2/run_id=manual__2025-04-05T17:14:18.319793+00:00/task_id=training_modelos_de_prueba permission to 509
[2025-04-05T17:15:54.426+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-04-05T17:14:18.319793+00:00 [running]> on host d8a8722a294d
[2025-04-05T17:15:54.653+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_modelos_de_prueba' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T17:14:18.319793+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T17:14:18.319793+00:00'
[2025-04-05T17:16:00.058+0000] {logging_mixin.py:149} WARNING - 2025/04/05 17:16:00 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-04-05T17:16:00.389+0000] {logging_mixin.py:149} WARNING - 2025/04/05 17:16:00 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-05T17:16:23.930+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-04-05T17:16:31.733+0000] {logging_mixin.py:149} WARNING - 2025/04/05 17:16:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-04-05T17:16:34.283+0000] {logging_mixin.py:149} WARNING - 2025/04/05 17:16:34 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-04-05T17:17:18.303+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-04-05T17:17:18.365+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_modelos_de_prueba, execution_date=20250405T171418, start_date=20250405T171553, end_date=20250405T171718
[2025-04-05T17:17:18.486+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-04-05T17:17:18.520+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
